const Colleges = [
    'Princeton University',
    'Massachusetts Institute of Technology',
    'Harvard University',
    'Yale University',
    'Stanford University',
    'University of Chicago',
    'University of Pennsylvania',
    'Johns Hopkins University',
    'California Institute of Technology',
    'Duke University',
    'Northwestern University',
    'Dartmouth College',
    'Brown University',
    'Vanderbilt University',
    'Washington University in St. Louis',
    'Rice University',
    'Cornell University',
    'Columbia University',
    'University of Notre Dame',
    'University of California-Los Angeles',
    'University of California-Berkeley',
    'Emory University',
    'Georgetown University',
    'Carnegie Mellon University',
    'University of Michigan-Ann Arbor',
    'University of Virginia',
    'University of Southern California',
    'New York University',
    'University of Florida',
    'University of North Carolina-Chapel Hill',
    'Wake Forest University',
    'Tufts University',
    'University of California-Santa Barbara',
    'University of California-San Diego',
    'University of California-Irvine',
    'University of Rochester',
    'Boston College',
    'University of California-Davis',
    'University of Texas-Austin',
    'University of Wisconsin-Madison',
    'College of William and Mary',
    'Boston University',
    'University of Illinois-Urbana-Champaign',
    'Georgia Institute of Technology',
    'Brandeis University',
    'Case Western Reserve University',
    'Tulane University',
    'Northeastern University',
    'University of Georgia',
    'Ohio State University-Columbus',
    'Lehigh University',
    'Purdue University',
    'Villanova University',
    'Rensselaer Polytechnic Institute',
    'Pepperdine University',
    'Florida State University',
    'Santa Clara University',
    'University of Miami',
    'University of Maryland',
    'University of Washington',
    'Rutgers University-New Brunswick',
    'Syracuse University',
    'University of Pittsburgh',
    'George Washington University',
    'University of Minnesota',
    'Virginia Polytechnic Institute and State University',
    'University of Connecticut',
    'Worcester Polytechnic Institute',
    'Texas A&M University-College Station',
    'University of Massachusetts-Amherst',
    'Yeshiva University',
    'Fordham University',
    'Indiana University-Bloomington',
    'Southern Methodist University',
    'American University',
    'North Carolina State University',
    'Pennsylvania State University-University Park',
    'Baylor University',
    'Clemson University',
    'Loyola Marymount University',
    'Michigan State University',
    'Stony Brook University',
    'Gonzaga University',
    'Binghamton University',
    'Marquette University',
    'Stevens Institute of Technology',
    'University of Iowa',
    'University of California-Santa Cruz',
    'Brigham Young University',
    'Colorado School of Mines',
    'Elon University',
    'Howard University',
    'Texas Christian University',
    'University of California-Riverside',
    'University of Buffalo',
    'University of Delaware',
    'University of California-Merced',
    'University of San Diego',
    'Auburn University',
    'University of Colorado-Boulder',
    'Clark University',
    'New Jersey Institute of Technology',
    'University of Illinois-Chicago',
    'University of South Florida',
    'University of Denver',
    'University of Oregon',
    'University of Utah',
    'Drexel University',
    'Miami University',
    'Saint Louis University',
    'University of Arizona',
    'University of San Francisco',
    'Rochester Institute of Technology',
    'SUNY College of Environmental Science and Forestry',
    'Creighton University',
    'Loyola University Chicago',
    'University of Tennessee',
    'University of South Carolina',
    'Rutgers University-Newark',
    'Fairfield University',
    'Temple University',
    'Arizona State University-Tempe',
    'Chapman University',
    'University of Vermont',
    'University of Kansas',
    'University of Missouri',
    'Illinois Institute of Technology',
    'Iowa State University',
    'Clarkson University',
    'Gallaudet University',
    'University of Dayton',
    'University of Oklahoma',
    'New School',
    'Samford University',
    'Rutgers University-Camden',
    'Thomas Jefferson University',
    'DePaul University',
    'Seattle University',
    'Seton Hall University',
    'University of Kentucky',
    'Drake University',
    'University of New Hampshire',
    'University of St. Thomas',
    'University of Tulsa',
    'George Mason University',
    'University of Alabama',
    'University of Central Florida',
    'California State University-Long Beach',
    'University of Maryland-Baltimore County',
    'Catholic University of America',
    'Simmons University',
    'University of La Verne',
    'University of Nebraska-Lincoln',
    'University of Texas-Dallas',
    'University of the Pacific',
    'Colorado State University',
    'CUNY-City College',
    'Duquesne University',
    'Michigan Technological University',
    'Quinnipiac University',
    'San Diego State University',
    'University of Cincinnati',
    'University of Mississippi',
    'Ohio University',
    'University of Arkansas',
    'Washington State University'
];

export default Colleges;