const MockRecs = [
    ["English I", 0],
    ["English II", 0],
    ["English III", 60.2],
    ["English IV", 3.4],
    ["Creative Writing", 85.6],
    ["American Literature", 39.4],
    ["Journalism", 46.0],
    ["Debate", 24.3],
    ["AP Language & Composition", 89.3],
    ["AP Literature & Composition", 51.0],
    ["Algebra I", 0],
    ["Algebra II", 0],
    ["Trigonometry", 6.5],
    ["Geometry", 4.5],
    ["AP Calculus AB", 87.8],
    ["AP Calculus BC", 45.4],
    ["Statistics", 48.8],
    ["Probability", 55.7],
    ["AP Statistics", 20.4],
    ["Biology", 0],
    ["Biology Honors", 0],
    ["AP Biology", 40.2],
    ["Chemistry", 0],
    ["Chemistry Honors", 0],
    ["AP Chemistry", 87.8],
    ["Physics", 40.3],
    ["Physics Honors", 75.4],
    ["AP Physics 1", 20.4],
    ["AP Physics 2", 19.4],
    ["AP Physics C: Mechanics", 25.3],
    ["AP Physics C: Electricity/Magnetism", 15.2],
    ["AP World History", 30.2],
    ["AP US History", 78.7],
    ["AP European History", 46.3],
    ["AP Psychology", 33.2],
    ["AP Macroeconomics", 40.5],
    ["AP Microeconomics", 36.8],
    ["AP Human Geography", 45.2],
    ["Economics", 50.3],
    ["Civics", 12.3],
    ["AP Computer Science A", 30.4],
    ["AP Computer Science Principles", 30.4],
    ["AP Art History", 22.3],
    ["AP Studio Art 2D", 10.6],
    ["AP Studio Art 3D", 18.4],
    ["Theater", 10.4],
    ["Music", 18.7],
    ["AP US Government and Politics", 59.8],
    ["AP Japanese", 30.3],
    ["AP Chinese", 20.1],
    ["AP German", 2],
    ["French I", 2],
    ["French II", 3],
    ["French III", 4],
    ["French IV", 1],
    ["AP French", 1],
    ["Spanish I", 0],
    ["Spanish II", 2],
    ["Spanish III", 3],
    ["Spanish IV", 4],
    ["AP Spanish", 0]
];

export default MockRecs;